#MYSQL_ROOT_PASSWORD: RoboShop@1
$ANSIBLE_VAULT;1.1;AES256
33613932656533666163336537383833653733356264366330336461396535346630356232396265
3136336338323962316261326530636163636338666639380a323832316336333537333061623931
65373835333839393162366165633439326337646532393765323163303231643262346331376561
3335623138313134650a356533303566663262366636353866656166636332636639383163373233
33326634343837376366323163353834313837323266333865663532396166373561626466393333
3466323563646566623962316639306130313562383261346463
