- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app_setup.yaml

- name: python setup
  ansible.builtin.import_role:
    name: common
    tasks_from: python_setup.yaml

- name: copy systemctl {{ component }}
  ansible.builtin.template:
    src: "{{ component }}.service.j2"
    dest : /etc/systemd/system/{{ component }}.service

- name: systemd_setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd_setup.yaml


- name: start and enable payment
  ansible.builtin.service:
    name: payment
    state: restarted
    enabled: yes