- name: html setup
  ansible.builtin.import_role:
    name: common
    tasks_from: html_setup.yaml

- name: nginx setup
  ansible.builtin.import_role:
    name: common
    tasks_from: nginx_setup.yaml

- name: copy nginx
  ansible.builtin.template:
    src: nginx.config.j2
    dest: /etc/nginx/nginx.conf
    

- name: start and enable nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes