- name: nodejs_setup
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs_setup.yaml

- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app_setup.yaml

- name: systemd_setup
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd_setup.yaml


- name: copy catalogue service 
  ansible.builtin.template:
    src: catalogue.service 
    dest: /etc/systemd/system/catalogue.service

- name: copy mongo repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: install mongodb client
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: present

- name: checking products
  ansible.builtin.command: mongosh --host "{{ MONGODB_HOST }}" --quiet --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
  register: catalogue_output

- name: loading the products
  ansible.builtin.shell: mongosh --host "{{ MONGODB_HOST }}" </app/db/master-data.js
  when: catalogue_output.stdout | int < 0


