- name: testing-1
  ansible.builtin.debug:
    msg: "Hi from testimg-1"

- name: setting dynamic variable
  ansible.builtin.set_fact:
    os: "debian"

- name: testing-2
  ansible.builtin.debug:
    msg: "Hi from testimg-2"

- name: testing-3
  ansible.builtin.debug:
    msg: "Hi from testimg-3"