- name: enable nodejs 20
  ansible.builtin.command: dnf module enable nodejs:20 -y

- name: install nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: present

- name: Install packages
  tags:
  - usingtags #we can use any word to represents tags
  community.general.npm:
    path: /app
