- name: system daemon reloaded
  ansible.builtin.systemd_service:
    daemon_reload: true
    name: "{{ component }}"

- name: start and enable
  ansible.builtin.service:
    name: "{{ component }}"
    state: restarted
    enabled: yes